### ISSUE TITLE
Panic on array with empty string interpolation

### ISSUE THREAD

**Issue by Emik03** [rhaiscript/rhai#598]
The following code snippet will panic.
```rust
use rhai::{Dynamic, Engine};

fn main() {
    Engine::new().eval::<Dynamic>("[`${}`]").ok();
}
```
This unwrap will need to be removed, likely replaced with a `ok_or`.
```rust
// src\ast\expr.rs:560:67
#[cfg(not(feature = "no_index"))]
Self::Array(x, ..) if self.is_constant() => {
    let mut arr = crate::Array::with_capacity(x.len());
    // The panic happens here in the 'unwrap' call.
    // TODO: Return syntax error if none rather than unwrapping.
    arr.extend(x.iter().map(|v| v.get_literal_value().unwrap()));
    Dynamic::from_array(arr)
}
```
Full stack trace:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.96s
     Running `target\debug\rhai-validator.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\ast\expr.rs:560:67
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library\std\src\panicking.rs:584       
   1: core::panicking::panic_fmt
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library\core\src\panicking.rs:142      
   2: core::panicking::panic
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library\core\src\panicking.rs:48       
   3: enum$<core::option::Option<rhai::types::dynamic::Dynamic>, 0, 12, Some>::unwrap<rhai::types::dynamic::Dynamic>
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\option.rs:775
   4: rhai::ast::expr::impl$20::get_literal_value::closure$0
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\ast\expr.rs:560
   5: core::iter::adapters::map::map_fold::closure$0<ref$<enum$<rhai::ast::expr::Expr> >,rhai::types::dynamic::Dynamic,tuple$<>,rhai::ast::expr::impl$20::get_literal_value::closure_env$0,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<rhai
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\iter\adapters\map.rs:84
   6: core::iter::traits::iterator::Iterator::fold<core::slice::iter::Iter<enum$<rhai::ast::expr::Expr> >,tuple$<>,core::iter::adapters::map::map_fold::closure_env$0<ref$<enum$<rhai::ast::expr::Expr> >,rhai::types::dynamic::Dynamic,tuple$<>,rhai::ast::expr::imp
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\iter\traits\iterator.rs:2370
   7: core::iter::adapters::map::impl$2::fold<rhai::types::dynamic::Dynamic,core::slice::iter::Iter<enum$<rhai::ast::expr::Expr> >,rhai::ast::expr::impl$20::get_literal_value::closure_env$0,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closur
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\iter\adapters\map.rs:124
   8: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::map::Map<core::slice::iter::Iter<enum$<rhai::ast::expr::Expr> >,rhai::ast::expr::impl$20::get_literal_value::closure_env$0>,alloc::vec::spec_extend::impl$1::spec_extend::closure_env$0<
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\iter\traits\iterator.rs:787
   9: alloc::vec::spec_extend::impl$1::spec_extend<rhai::types::dynamic::Dynamic,core::iter::adapters::map::Map<core::slice::iter::Iter<enum$<rhai::ast::expr::Expr> >,rhai::ast::expr::impl$20::get_literal_value::closure_env$0>,alloc::alloc::Global>
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\alloc\src\vec\spec_extend.rs:40  10: alloc::vec::impl$22::extend<rhai::types::dynamic::Dynamic,alloc::alloc::Global,core::iter::adapters::map::Map<core::slice::iter::Iter<enum$<rhai::ast::expr::Expr> >,rhai::ast::expr::impl$20::get_literal_value::closure_env$0> >
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\alloc\src\vec\mod.rs:2690      
  11: enum$<rhai::ast::expr::Expr>::get_literal_value
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\ast\expr.rs:560
  12: rhai::optimizer::optimize_expr
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\optimizer.rs:1046
  13: rhai::optimizer::optimize_stmt
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\optimizer.rs:862
  14: rhai::optimizer::optimize_stmt_block
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\optimizer.rs:281
  15: rhai::optimizer::optimize_top_level
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\optimizer.rs:1306
  16: rhai::optimizer::optimize_into_ast
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\optimizer.rs:1369
  17: rhai::engine::Engine::parse
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\parser.rs:3713
  18: rhai::engine::Engine::compile_with_scope_and_optimization_level<str,ref$<array$<str,1> > >       
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\compile.rs:225
  19: rhai::engine::Engine::eval_with_scope<rhai::types::dynamic::Dynamic>
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:67
  20: rhai::engine::Engine::eval
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:30
  21: rhai_validator::main
             at .\src\main.rs:36
  22: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,std::io::error::Error>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\ops\function.rs:248   
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\rhai-validator.exe` (exit code: 101)
 ```
 Ran on `cargo 1.63.0-nightly (8d42b0e87 2022-06-17)` and `rhai = "1.8.0"`.

**Comment by schungx** [comment]
Good catch.  Actually `get_literal_value` should not fail.

**Comment by schungx** [comment]
PR https://github.com/rhaiscript/rhai/pull/600 fixes this.  Thanks.
