### ISSUE TITLE
Panic on object map closure containing reference to non-existing variable

### ISSUE THREAD

**Issue by Emik03** [rhaiscript/rhai#599]
The following code snippet will panic.
```rust
use rhai::{Dynamic, Engine};

fn main() {
    Engine::new().eval::<Dynamic>("#{a:||b}").ok();
}
```
Edge-case will have to be put here instead of panicking.
```rust
// src\eval\stmt.rs:1018:21
if let Some((index, ..)) = scope.get_index(name) {
    // ...
} else {
    unreachable!("variable {} not found for sharing", name);
}
```
Full stack trace:
```
   Compiling rhai-validator v0.1.0 (C:\Users\Emik\Documents\rhai-validator)
    Finished dev [unoptimized + debuginfo] target(s) in 1.10s
     Running `target\debug\rhai-validator.exe`
thread 'main' panicked at 'internal error: entered unreachable code: variable b not found for sharing', C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\stmt.rs:1018:21     
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library\std\src\panicking.rs:584       
   1: core::panicking::panic_fmt
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library\core\src\panicking.rs:142      
   2: rhai::engine::Engine::eval_stmt
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\stmt.rs:1018
   3: rhai::engine::Engine::eval_stmt_block
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\stmt.rs:55
   4: rhai::engine::Engine::eval_expr
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\expr.rs:500
   5: rhai::engine::Engine::eval_expr
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\expr.rs:396
   6: rhai::engine::Engine::eval_stmt
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\stmt.rs:347
   7: rhai::engine::Engine::eval_stmt_block
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\eval\stmt.rs:55
   8: rhai::engine::Engine::eval_global_statements
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\func\call.rs:747
   9: rhai::engine::Engine::eval_ast_with_scope_raw
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:246
  10: rhai::engine::Engine::eval_ast_with_scope<rhai::types::dynamic::Dynamic>
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:192
  11: rhai::engine::Engine::eval_with_scope<rhai::types::dynamic::Dynamic>
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:72
  12: rhai::engine::Engine::eval
             at C:\Users\Emik\.cargo\registry\src\github.com-1ecc6299db9ec823\rhai-1.8.0\src\api\eval.rs:30
  13: rhai_validator::main
             at .\src\main.rs:36
  14: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,std::io::error::Error>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c\library\core\src\ops\function.rs:248   
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\rhai-validator.exe` (exit code: 101)

 *  The terminal process "C:\Users\Emik\.cargo\bin\cargo.exe 'run', '--package', 'rhai-validator', '--bin', 'rhai-validator'" terminated with exit code: 101. 
 ```
 Ran on `cargo 1.63.0-nightly (8d42b0e87 2022-06-17)` and `rhai = "1.8.0"`.

**Comment by schungx** [comment]
Good catch!  Will fix.

**Comment by schungx** [comment]
No reason why this place should panic instead of throwing a "variable not found" error.  What have I been thinking.

**Comment by schungx** [comment]
PR https://github.com/rhaiscript/rhai/pull/600 fixes this.  Thanks.
