### ISSUE TITLE
Panic when pre-evaluated import is used

### ISSUE THREAD

**Issue by SWW13** [rhaiscript/rhai#612]
```shell
cargo init
cargo add rhai
# edit files
RUST_BACKTRACE=1 cargo run
thread 'main' panicked at 'attempt to subtract with overflow', /github.com-1ecc6299db9ec823/rhai-1.8.0/src/eval/expr.rs:34:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
   3: rhai::eval::expr::<impl rhai::engine::Engine>::search_imports
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/eval/expr.rs:34:26
   4: rhai::func::call::<impl rhai::engine::Engine>::make_qualified_function_call
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/func/call.rs:1340:22
   5: rhai::eval::expr::<impl rhai::engine::Engine>::eval_fn_call_expr
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/eval/expr.rs:221:20
   6: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/eval/stmt.rs:235:17
   7: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/eval/stmt.rs:55:22
   8: rhai::func::script::<impl rhai::engine::Engine>::call_script_fn
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/func/script.rs:151:27
   9: rhai::api::call_fn::<impl rhai::engine::Engine>::_call_fn
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/api/call_fn.rs:274:22
  10: rhai::api::call_fn::<impl rhai::engine::Engine>::call_fn_raw
             at /github.com-1ecc6299db9ec823/rhai-1.8.0/src/api/call_fn.rs:165:9
  11: rhai_underflow::main
             at ./src/main.rs:16:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`main.rs`:
```rust
fn main() {
    let engine = rhai::Engine::new();
    let mut scope = rhai::Scope::new();
    let ast = engine.compile_file("underflow.rhai".into()).unwrap();
    let _ = engine.eval_ast_with_scope::<()>(&mut scope, &ast).unwrap();

    engine
        .call_fn_raw(
            &mut scope,
            &ast,
            false,
            true,
            "func_underflow",
            None,
            &mut [],
        )
        .unwrap();
}
```

`underflow.rhai`:
```rhai
import "test" as test;

fn func_underflow() {
    test::func();
}
```

`test.rhai`:
```rhai
fn func() {
    debug("test");
}
```

**Comment by schungx** [comment]
Yes, this should be considered a bug.  That is because you use `call_fn_raw` which is a low level API.  In addition, you skipped evaluating the body of the script, the the `import` statement is never run.

It should return with an error saying module `test` is not found.

It'll be fixed in the next release.  Thanks for catching this.
