### ISSUE TITLE
I get a panic from rhai 1.15

### ISSUE THREAD

**Issue by ejaa3** [rhaiscript/rhai#732]
I have a code where I try to get a map, something like this:

~~~ rust
let map: rhai::Map = engine.eval(script).map_err(MyError)?;
~~~

I run it with `RUST_BACKTRACE=1` and get the following since rhai 1.15 (it works fine on 1.14):

~~~
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:1399:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:950:21
   4: rhai::func::call::<impl rhai::engine::Engine>::make_qualified_function_call
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:1399:37
   5: rhai::func::call::<impl rhai::engine::Engine>::eval_fn_call_expr
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:1797:20
   6: rhai::eval::expr::<impl rhai::engine::Engine>::eval_expr
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/expr.rs:250:17
   7: rhai::func::call::<impl rhai::engine::Engine>::get_arg_value
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:721:9
   8: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain_arguments
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:491:45
   9: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:374:18
  10: rhai::eval::expr::<impl rhai::engine::Engine>::eval_expr
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/expr.rs:411:30
  11: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:283:33
  12: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block::{{closure}}
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:82:17
  13: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2304:21
  14: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:75:9
  15: rhai::func::script::<impl rhai::engine::Engine>::call_script_fn
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/script.rs:112:39
  16: rhai::func::call::<impl rhai::engine::Engine>::exec_fn_call
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:661:21
  17: rhai::func::call::<impl rhai::engine::Engine>::make_method_call
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/func/call.rs:982:25
  18: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:714:25
  19: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:934:64
  20: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:934:64
  21: rhai::eval::chaining::<impl rhai::engine::Engine>::eval_dot_index_chain
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/chaining.rs:417:17
  22: rhai::eval::expr::<impl rhai::engine::Engine>::eval_expr
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/expr.rs:411:30
  23: rhai::eval::expr::<impl rhai::engine::Engine>::eval_expr
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/expr.rs:265:37
  24: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:432:33
  25: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block::{{closure}}
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:82:17
  26: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2304:21
  27: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:75:9
  28: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_global_statements
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:990:9
  29: rhai::api::eval::<impl rhai::engine::Engine>::eval_ast_with_scope_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/api/eval.rs:264:17
  30: rhai::module::Module::eval_ast_as_new_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/module/mod.rs:2174:22
  31: rhai::module::resolvers::file::FileModuleResolver::impl_resolve
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/module/resolvers/file.rs:317:28
  32: <rhai::module::resolvers::file::FileModuleResolver as rhai::module::resolvers::ModuleResolver>::resolve_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/module/resolvers/file.rs:338:9
  33: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt::{{closure}}
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:909:29
  34: core::option::Option<T>::or_else
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:1549:21
  35: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:899:30
  36: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block::{{closure}}
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:82:17
  37: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:2304:21
  38: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_stmt_block
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:75:9
  39: rhai::eval::stmt::<impl rhai::engine::Engine>::eval_global_statements
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/eval/stmt.rs:990:9
  40: rhai::api::eval::<impl rhai::engine::Engine>::eval_ast_with_scope_raw
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/api/eval.rs:264:17
  41: rhai::api::eval::<impl rhai::engine::Engine>::eval_ast_with_scope
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/api/eval.rs:208:22
  42: rhai::api::eval::<impl rhai::engine::Engine>::eval_with_scope
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/api/eval.rs:77:9
  43: rhai::api::eval::<impl rhai::engine::Engine>::eval
             at /home/eduardo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rhai-1.15.1/src/api/eval.rs:35:9
  44: aquarelle::mapping::perform
             at ./src/mapping.rs:219:24
...
~~~

**Comment by schungx** [comment]
Can you share your script?

**Comment by schungx** [comment]
You can also pull from this master to check if it is really fixed.

Thanks!

**Comment by schungx** [comment]
Closing this for now.  Pls comment if there is still a prob.
